package com.ideacome.common.db.mapper;

import com.ideacome.common.db.domain.SysRoleFunction;
import com.ideacome.common.db.domain.SysRoleFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int countByExample(SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int deleteByExample(SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int insert(SysRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int insertSelective(SysRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    List<SysRoleFunction> selectByExample(SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    SysRoleFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRoleFunction record, @Param("example") SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int updateByExample(@Param("record") SysRoleFunction record, @Param("example") SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Fri Dec 07 10:51:41 CST 2018
     */
    int updateByPrimaryKey(SysRoleFunction record);
}