package com.ideacome.common.db.domain;

import java.util.Date;

public class InsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.real_name
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.password
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.business_mobile
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private String businessMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.wechat_open_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private String wechatOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.create_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.modify_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user.deleted_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Long deletedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.id
     *
     * @return the value of ins_user.id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.id
     *
     * @param id the value for ins_user.id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.real_name
     *
     * @return the value of ins_user.real_name
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.real_name
     *
     * @param realName the value for ins_user.real_name
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.password
     *
     * @return the value of ins_user.password
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.password
     *
     * @param password the value for ins_user.password
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.business_mobile
     *
     * @return the value of ins_user.business_mobile
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public String getBusinessMobile() {
        return businessMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.business_mobile
     *
     * @param businessMobile the value for ins_user.business_mobile
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setBusinessMobile(String businessMobile) {
        this.businessMobile = businessMobile == null ? null : businessMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.wechat_open_id
     *
     * @return the value of ins_user.wechat_open_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public String getWechatOpenId() {
        return wechatOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.wechat_open_id
     *
     * @param wechatOpenId the value for ins_user.wechat_open_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setWechatOpenId(String wechatOpenId) {
        this.wechatOpenId = wechatOpenId == null ? null : wechatOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.create_time
     *
     * @return the value of ins_user.create_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.create_time
     *
     * @param createTime the value for ins_user.create_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.modify_time
     *
     * @return the value of ins_user.modify_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.modify_time
     *
     * @param modifyTime the value for ins_user.modify_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user.deleted_id
     *
     * @return the value of ins_user.deleted_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Long getDeletedId() {
        return deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user.deleted_id
     *
     * @param deletedId the value for ins_user.deleted_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setDeletedId(Long deletedId) {
        this.deletedId = deletedId;
    }
}