package com.ideacome.common.db.domain;

import java.util.Date;

public class InsUserExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user_ext.id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user_ext.user_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user_ext.create_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user_ext.modify_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ins_user_ext.deleted_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    private Long deletedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user_ext.id
     *
     * @return the value of ins_user_ext.id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user_ext.id
     *
     * @param id the value for ins_user_ext.id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user_ext.user_id
     *
     * @return the value of ins_user_ext.user_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user_ext.user_id
     *
     * @param userId the value for ins_user_ext.user_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user_ext.create_time
     *
     * @return the value of ins_user_ext.create_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user_ext.create_time
     *
     * @param createTime the value for ins_user_ext.create_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user_ext.modify_time
     *
     * @return the value of ins_user_ext.modify_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user_ext.modify_time
     *
     * @param modifyTime the value for ins_user_ext.modify_time
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ins_user_ext.deleted_id
     *
     * @return the value of ins_user_ext.deleted_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public Long getDeletedId() {
        return deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ins_user_ext.deleted_id
     *
     * @param deletedId the value for ins_user_ext.deleted_id
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    public void setDeletedId(Long deletedId) {
        this.deletedId = deletedId;
    }
}