package com.ideacome.common.db.persistence;

import com.ideacome.common.db.domain.InsUserExt;
import com.ideacome.common.db.domain.InsUserExtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InsUserExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int countByExample(InsUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int deleteByExample(InsUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int insert(InsUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int insertSelective(InsUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    List<InsUserExt> selectByExample(InsUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    InsUserExt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") InsUserExt record, @Param("example") InsUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByExample(@Param("record") InsUserExt record, @Param("example") InsUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(InsUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user_ext
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByPrimaryKey(InsUserExt record);
}