package com.ideacome.common.db.mapper;

import com.ideacome.common.db.domain.InsUser;
import com.ideacome.common.db.domain.InsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int countByExample(InsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int deleteByExample(InsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int insert(InsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int insertSelective(InsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    List<InsUser> selectByExample(InsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    InsUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") InsUser record, @Param("example") InsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByExample(@Param("record") InsUser record, @Param("example") InsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(InsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ins_user
     *
     * @mbggenerated Tue Dec 04 11:09:09 CST 2018
     */
    int updateByPrimaryKey(InsUser record);
}