package com.ideacome.common.db.domain;

import java.util.Date;

public class SysFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.id
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_code
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private String funCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_name
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private String funName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_type
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private Byte funType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.action_url
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private String actionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.parent_id
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.icon
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.order
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.description
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.creator
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.modifier
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.add_time
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.modify_time
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.sys_flag
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    private Byte sysFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.id
     *
     * @return the value of sys_function.id
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.id
     *
     * @param id the value for sys_function.id
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_code
     *
     * @return the value of sys_function.fun_code
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public String getFunCode() {
        return funCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_code
     *
     * @param funCode the value for sys_function.fun_code
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setFunCode(String funCode) {
        this.funCode = funCode == null ? null : funCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_name
     *
     * @return the value of sys_function.fun_name
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public String getFunName() {
        return funName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_name
     *
     * @param funName the value for sys_function.fun_name
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setFunName(String funName) {
        this.funName = funName == null ? null : funName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_type
     *
     * @return the value of sys_function.fun_type
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public Byte getFunType() {
        return funType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_type
     *
     * @param funType the value for sys_function.fun_type
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setFunType(Byte funType) {
        this.funType = funType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.action_url
     *
     * @return the value of sys_function.action_url
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.action_url
     *
     * @param actionUrl the value for sys_function.action_url
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl == null ? null : actionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.parent_id
     *
     * @return the value of sys_function.parent_id
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.parent_id
     *
     * @param parentId the value for sys_function.parent_id
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.icon
     *
     * @return the value of sys_function.icon
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.icon
     *
     * @param icon the value for sys_function.icon
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.order
     *
     * @return the value of sys_function.order
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.order
     *
     * @param order the value for sys_function.order
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.description
     *
     * @return the value of sys_function.description
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.description
     *
     * @param description the value for sys_function.description
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.creator
     *
     * @return the value of sys_function.creator
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.creator
     *
     * @param creator the value for sys_function.creator
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.modifier
     *
     * @return the value of sys_function.modifier
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.modifier
     *
     * @param modifier the value for sys_function.modifier
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.add_time
     *
     * @return the value of sys_function.add_time
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.add_time
     *
     * @param addTime the value for sys_function.add_time
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.modify_time
     *
     * @return the value of sys_function.modify_time
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.modify_time
     *
     * @param modifyTime the value for sys_function.modify_time
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.sys_flag
     *
     * @return the value of sys_function.sys_flag
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.sys_flag
     *
     * @param sysFlag the value for sys_function.sys_flag
     *
     * @mbggenerated Fri Dec 07 10:29:52 CST 2018
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }
}